[package]
name = "git-secret"
version = "0.1.0"
authors = ["sobolevn <mail@sobolevn.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33", features = ["yaml", "suggestions", "color"]}
